version: "2"

services:
  app:
    restart: always
    container_name: task-tracker
    build: .
    depends_on:
      - db
    ports:
      - '3001:3001'
    links:
      - db
  db:
      container_name: mongodb
      image: mongo
      ports:
        - '27017:27017'
